<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('id' => 1, 'ar_name' => 'أفغنستان', 'en_name' => 'Afghanistan', 'code' => 'AFG'),
            array('id' => 2, 'ar_name' => 'ألبانيا', 'en_name' => 'Albania', 'code' => 'ALB'),
            array('id' => 3, 'ar_name' => 'الجزائر', 'en_name' => 'Algeria', 'code' => 'DZA'),
            array('id' => 4, 'ar_name' => 'ساموا الأمريكية', 'en_name' => 'American Samoa', 'code' => 'ASM'),
            array('id' => 5, 'ar_name' => 'أندورا', 'en_name' => 'Andorra', 'code' => '0'),
            array('id' => 6, 'ar_name' => 'أنغولا', 'en_name' => 'Angola', 'code' => 'AGO'),
            array('id' => 7, 'ar_name' => 'أنغيلا', 'en_name' => 'Anguilla', 'code' => 'AIA'),
            array('id' => 8, 'ar_name' => 'أنتاركتيكا', 'en_name' => 'Antarctica', 'code' => '0'),
            array('id' => 9, 'ar_name' => 'أنتيغوا وبربودا', 'en_name' => 'Antigua and Barbuda', 'code' => 'ATG'),
            array('id' => 10, 'ar_name' => 'الأرجنتين', 'en_name' => 'Argentina', 'code' => 'ARG'),
            array('id' => 11, 'ar_name' => 'أرمينيا', 'en_name' => 'Armenia', 'code' => 'ARM'),
            array('id' => 12, 'ar_name' => 'أروبا', 'en_name' => 'Aruba', 'code' => 'ABW'),
            array('id' => 13, 'ar_name' => 'أستراليا', 'en_name' => 'Australia', 'code' => 'AUS'),
            array('id' => 14, 'ar_name' => 'النمسا', 'en_name' => 'Austria', 'code' => 'AUT'),
            array('id' => 15, 'ar_name' => 'أذربيجان', 'en_name' => 'Azerbaijan', 'code' => 'AZE'),
            array('id' => 16, 'ar_name' => 'البهاما', 'en_name' => 'Bahamas', 'code' => 'BHS'),
            array('id' => 17, 'ar_name' => 'البحرين', 'en_name' => 'Bahrain', 'code' => 'BHR'),
            array('id' => 18, 'ar_name' => 'بنغلاديش', 'en_name' => 'Bangladesh', 'code' => 'BGD'),
            array('id' => 19, 'ar_name' => 'بربادوس', 'en_name' => 'Barbados', 'code' => 'BRB'),
            array('id' => 20, 'ar_name' => 'بيلاروسيا', 'en_name' => 'Belarus', 'code' => 'BLR'),
            array('id' => 21, 'ar_name' => 'بلجيكا', 'en_name' => 'Belgium', 'code' => 'BEL'),
            array('id' => 22, 'ar_name' => 'بيليز', 'en_name' => 'Belize', 'code' => 'BLZ'),
            array('id' => 23, 'ar_name' => 'بنين', 'en_name' => 'Benin', 'code' => 'BEN'),
            array('id' => 24, 'ar_name' => 'برمودا', 'en_name' => 'Bermuda', 'code' => 'BMU'),
            array('id' => 25, 'ar_name' => 'بوتان', 'en_name' => 'Bhutan', 'code' => 'BTN'),
            array('id' => 26, 'ar_name' => 'بوليفيا', 'en_name' => 'Bolivia', 'code' => 'BOL'),
            array('id' => 27, 'ar_name' => 'البوسنة والهرسك', 'en_name' => 'Bosnia and Herzegovina', 'code' => 'BIH'),
            array('id' => 28, 'ar_name' => 'بوتسوانا', 'en_name' => 'Botswana', 'code' => 'BWA'),
            array('id' => 29, 'ar_name' => 'جزيرة بوفيت', 'en_name' => 'Bouvet Island', 'code' => '0'),
            array('id' => 30, 'ar_name' => 'البرازيل', 'en_name' => 'Brazil', 'code' => 'BRA'),
            array('id' => 31, 'ar_name' => 'إقليم المحيط البريطاني الهندي', 'en_name' => 'British Indian Ocean Territory', 'code' => '0'),
            array('id' => 32, 'ar_name' => 'بروناي دار السلام', 'en_name' => 'Brunei Darussalam', 'code' => 'BRN'),
            array('id' => 33, 'ar_name' => 'بلغاريا', 'en_name' => 'Bulgaria', 'code' => 'BGR'),
            array('id' => 34, 'ar_name' => 'بوركينا فاسو', 'en_name' => 'Burkina Faso', 'code' => 'BFA'),
            array('id' => 35, 'ar_name' => 'بوروندي', 'en_name' => 'Burundi', 'code' => 'BDI'),
            array('id' => 36, 'ar_name' => 'كمبوديا', 'en_name' => 'Cambodia', 'code' => 'KHM'),
            array('id' => 37, 'ar_name' => 'الكاميرون', 'en_name' => 'Cameroon', 'code' => 'CMR'),
            array('id' => 38, 'ar_name' => 'كندا', 'en_name' => 'Canada', 'code' => 'CAN'),
            array('id' => 39, 'ar_name' => 'كيب فيردي', 'en_name' => 'Cape Verde', 'code' => 'CPV'),
            array('id' => 40, 'ar_name' => 'جزر كايمان', 'en_name' => 'Cayman Islands', 'code' => 'CYM'),
            array('id' => 41, 'ar_name' => 'جمهورية افريقيا الوسطى', 'en_name' => 'Central African Republic', 'code' => 'CAF'),
            array('id' => 42, 'ar_name' => 'تشاد', 'en_name' => 'Chad', 'code' => 'TCD'),
            array('id' => 43, 'ar_name' => 'شيلي', 'en_name' => 'Chile', 'code' => 'CHL'),
            array('id' => 44, 'ar_name' => 'الصين', 'en_name' => 'China', 'code' => 'CHN'),
            array('id' => 45, 'ar_name' => 'جزيرة الكريسماس', 'en_name' => 'Christmas Island', 'code' => '0'),
            array('id' => 46, 'ar_name' => 'جزر كوكوس (كيلينغ)', 'en_name' => 'Cocos (Keeling) Islands', 'code' => '0'),
            array('id' => 47, 'ar_name' => 'كولومبيا', 'en_name' => 'Colombia', 'code' => 'COL'),
            array('id' => 48, 'ar_name' => 'جزر القمر', 'en_name' => 'Comoros', 'code' => 'COM'),
            array('id' => 49, 'ar_name' => 'الكونغو', 'en_name' => 'Congo', 'code' => 'COG'),
            array('id' => 50, 'ar_name' => 'جمهورية الكونغو الديمقراطية', 'en_name' => 'Congo, the Democratic Republic of the', 'code' => 'COD'),
            array('id' => 51, 'ar_name' => 'جزر كوك', 'en_name' => 'Cook Islands', 'code' => 'COK'),
            array('id' => 52, 'ar_name' => 'كوستاريكا', 'en_name' => 'Costa Rica', 'code' => 'CRI'),
            array('id' => 53, 'ar_name' => 'ساحل العاج', 'en_name' => 'Cote DIvoire', 'code' => 'CIV'),
            array('id' => 54, 'ar_name' => 'كرواتيا', 'en_name' => 'Croatia', 'code' => 'HRV'),
            array('id' => 55, 'ar_name' => 'كوبا', 'en_name' => 'Cuba', 'code' => 'CUB'),
            array('id' => 56, 'ar_name' => 'قبرص', 'en_name' => 'Cyprus', 'code' => 'CYP'),
            array('id' => 57, 'ar_name' => 'الجمهورية التشيكية', 'en_name' => 'Czech Republic', 'code' => 'CZE'),
            array('id' => 58, 'ar_name' => 'الدنمارك', 'en_name' => 'Denmark', 'code' => 'DNK'),
            array('id' => 59, 'ar_name' => 'جيبوتي', 'en_name' => 'Djibouti', 'code' => 'DJI'),
            array('id' => 60, 'ar_name' => 'دومينيكا', 'en_name' => 'Dominica', 'code' => 'DMA'),
            array('id' => 61, 'ar_name' => 'جمهورية الدومنيكان', 'en_name' => 'Dominican Republic', 'code' => 'DOM'),
            array('id' => 62, 'ar_name' => 'الاكوادور', 'en_name' => 'Ecuador', 'code' => 'ECU'),
            array('id' => 63, 'ar_name' => 'مصر', 'en_name' => 'Egypt', 'code' => 'EGY'),
            array('id' => 64, 'ar_name' => 'السلفادور', 'en_name' => 'El Salvador', 'code' => 'SLV'),
            array('id' => 65, 'ar_name' => 'غينيا الإستوائية', 'en_name' => 'Equatorial Guinea', 'code' => 'GNQ'),
            array('id' => 66, 'ar_name' => 'إريتريا', 'en_name' => 'Eritrea', 'code' => 'ERI'),
            array('id' => 67, 'ar_name' => 'إستونيا', 'en_name' => 'Estonia', 'code' => 'EST'),
            array('id' => 68, 'ar_name' => 'أثيوبيا', 'en_name' => 'Ethiopia', 'code' => 'ETH'),
            array('id' => 69, 'ar_name' => 'جزر فوكلاند', 'en_name' => 'Falkland Islands (Malvinas)', 'code' => 'FLK'),
            array('id' => 70, 'ar_name' => 'جزر فاروس', 'en_name' => 'Faroe Islands', 'code' => 'FRO'),
            array('id' => 71, 'ar_name' => 'فيجي ', 'en_name' => 'Fiji', 'code' => 'FJI'),
            array('id' => 72, 'ar_name' => 'فنلندا', 'en_name' => 'Finland', 'code' => 'FIN'),
            array('id' => 73, 'ar_name' => 'فرنسا', 'en_name' => 'France', 'code' => 'FRA'),
            array('id' => 74, 'ar_name' => 'غيانا الفرنسية', 'en_name' => 'French Guiana', 'code' => 'GUF'),
            array('id' => 75, 'ar_name' => 'بولينيزيا الفرنسية', 'en_name' => 'French Polynesia', 'code' => 'PYF'),
            array('id' => 76, 'ar_name' => 'المناطق الجنوبية لفرنسا', 'en_name' => 'French Southern Territories', 'code' => '0'),
            array('id' => 77, 'ar_name' => 'جابون', 'en_name' => 'Gabon', 'code' => 'GAB'),
            array('id' => 78, 'ar_name' => 'غامبيا', 'en_name' => 'Gambia', 'code' => 'GMB'),
            array('id' => 79, 'ar_name' => 'جورجيا', 'en_name' => 'Georgia', 'code' => 'GEO'),
            array('id' => 80, 'ar_name' => 'ألمانيا', 'en_name' => 'Germany', 'code' => 'DEU'),
            array('id' => 81, 'ar_name' => 'غانا', 'en_name' => 'Ghana', 'code' => 'GHA'),
            array('id' => 82, 'ar_name' => 'جبل طارق', 'en_name' => 'Gibraltar', 'code' => 'GIB'),
            array('id' => 83, 'ar_name' => 'اليونان', 'en_name' => 'Greece', 'code' => 'GRC'),
            array('id' => 84, 'ar_name' => 'الأرض الخضراء', 'en_name' => 'Greenland', 'code' => 'GRL'),
            array('id' => 85, 'ar_name' => 'غرينادا', 'en_name' => 'Grenada', 'code' => 'GRD'),
            array('id' => 86, 'ar_name' => 'غوادلوب', 'en_name' => 'Guadeloupe', 'code' => 'GLP'),
            array('id' => 87, 'ar_name' => 'غوام', 'en_name' => 'Guam', 'code' => 'GUM'),
            array('id' => 88, 'ar_name' => 'جواتيمالا', 'en_name' => 'Guatemala', 'code' => 'GTM'),
            array('id' => 89, 'ar_name' => 'غينيا', 'en_name' => 'Guinea', 'code' => 'GIN'),
            array('id' => 90, 'ar_name' => 'غينيا بيساو', 'en_name' => 'Guinea-Bissau', 'code' => 'GNB'),
            array('id' => 91, 'ar_name' => 'غويانا', 'en_name' => 'Guyana', 'code' => 'GUY'),
            array('id' => 92, 'ar_name' => 'هايتي', 'en_name' => 'Haiti', 'code' => 'HTI'),
            array('id' => 93, 'ar_name' => 'قلب الجزيرة وجزر ماكدونالز', 'en_name' => 'Heard Island and Mcdonald Islands', 'code' => '0'),
            array('id' => 94, 'ar_name' => 'الفاتيكان', 'en_name' => 'Holy See (Vatican City State)', 'code' => 'VAT'),
            array('id' => 95, 'ar_name' => 'هندوراس', 'en_name' => 'Honduras', 'code' => 'HND'),
            array('id' => 97, 'ar_name' => 'هنغاريا', 'en_name' => 'Hungary', 'code' => 'HUN'),
            array('id' => 98, 'ar_name' => 'أيسلندا', 'en_name' => 'Iceland', 'code' => 'ISL'),
            array('id' => 99, 'ar_name' => 'الهند', 'en_name' => 'India', 'code' => 'IND'),
            array('id' => 100, 'ar_name' => 'إندونيسيا', 'en_name' => 'Indonesia', 'code' => 'IDN'),
            array('id' => 101, 'ar_name' => 'إيران, ISLAMIC REPUBLIC OF', 'en_name' => 'Iran, Islamic Republic of', 'code' => 'IRN'),
            array('id' => 102, 'ar_name' => 'العراق', 'en_name' => 'Iraq', 'code' => 'IRQ'),
            array('id' => 103, 'ar_name' => 'إيرلندا', 'en_name' => 'Ireland', 'code' => 'IRL'),
            array('id' => 105, 'ar_name' => 'إيطاليا', 'en_name' => 'Italy', 'code' => 'ITA'),
            array('id' => 106, 'ar_name' => 'جامايكا', 'en_name' => 'Jamaica', 'code' => 'JAM'),
            array('id' => 107, 'ar_name' => 'اليابان', 'en_name' => 'Japan', 'code' => 'JPN'),
            array('id' => 108, 'ar_name' => 'الأردن', 'en_name' => 'Jordan', 'code' => 'JOR'),
            array('id' => 109, 'ar_name' => 'كازاخستان', 'en_name' => 'Kazakhstan', 'code' => 'KAZ'),
            array('id' => 110, 'ar_name' => 'كينيا', 'en_name' => 'Kenya', 'code' => 'KEN'),
            array('id' => 111, 'ar_name' => 'كيريباتي', 'en_name' => 'Kiribati', 'code' => 'KIR'),
            array('id' => 112, 'ar_name' => 'كوريا، الجمهورية الشعبية الديمقراطية', 'en_name' => 'Korea, Democratic People Republic of', 'code' => 'PRK'),
            array('id' => 113, 'ar_name' => 'جمهورية كوريا', 'en_name' => 'Korea, Republic of', 'code' => 'KOR'),
            array('id' => 114, 'ar_name' => 'الكويت', 'en_name' => 'Kuwait', 'code' => 'KWT'),
            array('id' => 115, 'ar_name' => 'قرغيزستان', 'en_name' => 'Kyrgyzstan', 'code' => 'KGZ'),
            array('id' => 116, 'ar_name' => 'جمهورية لاو الديمقراطية الشعبية', 'en_name' => 'Lao People Democratic Republic', 'code' => 'LAO'),
            array('id' => 117, 'ar_name' => 'لاتفيا', 'en_name' => 'Latvia', 'code' => 'LVA'),
            array('id' => 118, 'ar_name' => 'لبنان', 'en_name' => 'Lebanon', 'code' => 'LBN'),
            array('id' => 119, 'ar_name' => 'ليسوتو', 'en_name' => 'Lesotho', 'code' => 'LSO'),
            array('id' => 120, 'ar_name' => 'ليبيريا', 'en_name' => 'Liberia', 'code' => 'LBR'),
            array('id' => 121, 'ar_name' => 'الجماهيرية العربية الليبية', 'en_name' => 'Libyan Arab Jamahiriya', 'code' => 'LBY'),
            array('id' => 122, 'ar_name' => 'ليختنشتاين', 'en_name' => 'Liechtenstein', 'code' => 'LIE'),
            array('id' => 123, 'ar_name' => 'ليثوانيا', 'en_name' => 'Lithuania', 'code' => 'LTU'),
            array('id' => 124, 'ar_name' => 'لوكسمبورغ', 'en_name' => 'Luxembourg', 'code' => 'LUX'),
            array('id' => 125, 'ar_name' => 'ماكاو', 'en_name' => 'Macao', 'code' => 'MAC'),
            array('id' => 126, 'ar_name' => 'مقدونيا ، جمهورية يوغسلاف السابقة', 'en_name' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MKD'),
            array('id' => 127, 'ar_name' => 'مدغشقر', 'en_name' => 'Madagascar', 'code' => 'MDG'),
            array('id' => 128, 'ar_name' => 'ملاوي', 'en_name' => 'Malawi', 'code' => 'MWI'),
            array('id' => 129, 'ar_name' => 'ماليزيا', 'en_name' => 'Malaysia', 'code' => 'MYS'),
            array('id' => 130, 'ar_name' => 'جزر المالديف', 'en_name' => 'Maldives', 'code' => 'MDV'),
            array('id' => 131, 'ar_name' => 'مالي', 'en_name' => 'Mali', 'code' => 'MLI'),
            array('id' => 132, 'ar_name' => 'مالطا', 'en_name' => 'Malta', 'code' => 'MLT'),
            array('id' => 133, 'ar_name' => 'جزر مارشال', 'en_name' => 'Marshall Islands', 'code' => 'MHL'),
            array('id' => 134, 'ar_name' => 'مارتينيك', 'en_name' => 'Martinique', 'code' => 'MTQ'),
            array('id' => 135, 'ar_name' => 'موريتانيا', 'en_name' => 'Mauritania', 'code' => 'MRT'),
            array('id' => 136, 'ar_name' => 'موريشيوس', 'en_name' => 'Mauritius', 'code' => 'MUS'),
            array('id' => 137, 'ar_name' => 'مايوت', 'en_name' => 'Mayotte', 'code' => '0'),
            array('id' => 138, 'ar_name' => 'المكسيك', 'en_name' => 'Mexico', 'code' => 'MEX'),
            array('id' => 139, 'ar_name' => 'ميكرونيسيا ', 'en_name' => 'Micronesia, Federated States of', 'code' => 'FSM'),
            array('id' => 140, 'ar_name' => 'جمهورية مولدوفا', 'en_name' => 'Moldova, Republic of', 'code' => 'MDA'),
            array('id' => 141, 'ar_name' => 'موناكو', 'en_name' => 'Monaco', 'code' => 'MCO'),
            array('id' => 142, 'ar_name' => 'منغوليا', 'en_name' => 'Mongolia', 'code' => 'MNG'),
            array('id' => 143, 'ar_name' => 'مونتسيرات', 'en_name' => 'Montserrat', 'code' => 'MSR'),
            array('id' => 144, 'ar_name' => 'المغرب', 'en_name' => 'Morocco', 'code' => 'MAR'),
            array('id' => 145, 'ar_name' => 'موزامبيق', 'en_name' => 'Mozambique', 'code' => 'MOZ'),
            array('id' => 146, 'ar_name' => 'ميانمار', 'en_name' => 'Myanmar', 'code' => 'MMR'),
            array('id' => 147, 'ar_name' => 'ناميبيا', 'en_name' => 'Namibia', 'code' => 'NAM'),
            array('id' => 148, 'ar_name' => 'ناورو', 'en_name' => 'Nauru', 'code' => 'NRU'),
            array('id' => 149, 'ar_name' => 'النيبال', 'en_name' => 'Nepal', 'code' => 'NPL'),
            array('id' => 150, 'ar_name' => 'هولندا', 'en_name' => 'Netherlands', 'code' => 'NLD'),
            array('id' => 151, 'ar_name' => 'جزر الأنتيل الهولندية', 'en_name' => 'Netherlands Antilles', 'code' => 'ANT'),
            array('id' => 152, 'ar_name' => 'كاليدونيا الجديدة', 'en_name' => 'New Caledonia', 'code' => 'NCL'),
            array('id' => 153, 'ar_name' => 'نيوزيلاندا', 'en_name' => 'New Zealand', 'code' => 'NZL'),
            array('id' => 154, 'ar_name' => 'نيكاراغوا', 'en_name' => 'Nicaragua', 'code' => 'NIC'),
            array('id' => 155, 'ar_name' => 'النيجر', 'en_name' => 'Niger', 'code' => 'NER'),
            array('id' => 156, 'ar_name' => 'نيجيريا', 'en_name' => 'Nigeria', 'code' => 'NGA'),
            array('id' => 157, 'ar_name' => 'نيوي', 'en_name' => 'Niue', 'code' => 'NIU'),
            array('id' => 158, 'ar_name' => 'جزيرة نورفولك', 'en_name' => 'Norfolk Island', 'code' => 'NFK'),
            array('id' => 159, 'ar_name' => 'جزر ماريانا الشمالية', 'en_name' => 'Northern Mariana Islands', 'code' => 'MNP'),
            array('id' => 160, 'ar_name' => 'النرويج', 'en_name' => 'Norway', 'code' => 'NOR'),
            array('id' => 161, 'ar_name' => 'عمان', 'en_name' => 'Oman', 'code' => 'OMN'),
            array('id' => 162, 'ar_name' => 'باكستان', 'en_name' => 'Pakistan', 'code' => 'PAK'),
            array('id' => 163, 'ar_name' => 'بالاو', 'en_name' => 'Palau', 'code' => 'PLW'),
            array('id' => 164, 'ar_name' => 'فلسطين', 'en_name' => 'Palestine', 'code' => '0'),
            array('id' => 165, 'ar_name' => 'بنما', 'en_name' => 'Panama', 'code' => 'PAN'),
            array('id' => 166, 'ar_name' => 'بابوا غينيا الجديدة', 'en_name' => 'Papua New Guinea', 'code' => 'PNG'),
            array('id' => 167, 'ar_name' => 'باراغواي', 'en_name' => 'Paraguay', 'code' => 'PRY'),
            array('id' => 168, 'ar_name' => 'بيرو', 'en_name' => 'Peru', 'code' => 'PER'),
            array('id' => 169, 'ar_name' => 'فيلبيني', 'en_name' => 'Philippines', 'code' => 'PHL'),
            array('id' => 170, 'ar_name' => 'بيتكيرن', 'en_name' => 'Pitcairn', 'code' => 'PCN'),
            array('id' => 171, 'ar_name' => 'بولندا', 'en_name' => 'Poland', 'code' => 'POL'),
            array('id' => 172, 'ar_name' => 'البرتغال', 'en_name' => 'Portugal', 'code' => 'PRT'),
            array('id' => 173, 'ar_name' => 'بورتوريكو', 'en_name' => 'Puerto Rico', 'code' => 'PRI'),
            array('id' => 174, 'ar_name' => 'قطر', 'en_name' => 'Qatar', 'code' => 'QAT'),
            array('id' => 175, 'ar_name' => 'ريونيون', 'en_name' => 'Reunion', 'code' => 'REU'),
            array('id' => 176, 'ar_name' => 'رومانيا', 'en_name' => 'Romania', 'code' => 'ROM'),
            array('id' => 177, 'ar_name' => 'روسيا', 'en_name' => 'Russian Federation', 'code' => 'RUS'),
            array('id' => 178, 'ar_name' => 'رواندا', 'en_name' => 'Rwanda', 'code' => 'RWA'),
            array('id' => 179, 'ar_name' => 'سانت هيلينا', 'en_name' => 'Saint Helena', 'code' => 'SHN'),
            array('id' => 180, 'ar_name' => 'سانت كيتس ونيفيس', 'en_name' => 'Saint Kitts and Nevis', 'code' => 'KNA'),
            array('id' => 181, 'ar_name' => 'سانت لوسيا', 'en_name' => 'Saint Lucia', 'code' => 'LCA'),
            array('id' => 182, 'ar_name' => 'سانت بيير وميكلون', 'en_name' => 'Saint Pierre and Miquelon', 'code' => 'SPM'),
            array('id' => 183, 'ar_name' => 'سانت فنسنت وجزر غرينادين', 'en_name' => 'Saint Vincent and the Grenadines', 'code' => 'VCT'),
            array('id' => 184, 'ar_name' => 'ساموا', 'en_name' => 'Samoa', 'code' => 'WSM'),
            array('id' => 185, 'ar_name' => 'سان مارينو', 'en_name' => 'San Marino', 'code' => 'SMR'),
            array('id' => 186, 'ar_name' => 'ساو تومي وبرينسيبي', 'en_name' => 'Sao Tome and Principe', 'code' => 'STP'),
            array('id' => 187, 'ar_name' => 'المملكة العربية السعودية', 'en_name' => 'Saudi Arabia', 'code' => 'SAU'),
            array('id' => 188, 'ar_name' => 'السنغال', 'en_name' => 'Senegal', 'code' => 'SEN'),
            array('id' => 190, 'ar_name' => 'سيشل', 'en_name' => 'Seychelles', 'code' => 'SYC'),
            array('id' => 191, 'ar_name' => 'سيراليون', 'en_name' => 'Sierra Leone', 'code' => 'SLE'),
            array('id' => 192, 'ar_name' => 'سنغافورة', 'en_name' => 'Singapore', 'code' => 'SGP'),
            array('id' => 193, 'ar_name' => 'سلوفاكيا', 'en_name' => 'Slovakia', 'code' => 'SVK'),
            array('id' => 194, 'ar_name' => 'سلوفينيا', 'en_name' => 'Slovenia', 'code' => 'SVN'),
            array('id' => 195, 'ar_name' => 'جزر سليمان', 'en_name' => 'Solomon Islands', 'code' => 'SLB'),
            array('id' => 196, 'ar_name' => 'الصومال', 'en_name' => 'Somalia', 'code' => 'SOM'),
            array('id' => 197, 'ar_name' => 'جنوب أفريقيا', 'en_name' => 'South Africa', 'code' => 'ZAF'),
            array('id' => 198, 'ar_name' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', 'en_name' => 'South Georgia and the South Sandwich Islands', 'code' => '0'),
            array('id' => 199, 'ar_name' => 'إسبانيا', 'en_name' => 'Spain', 'code' => 'ESP'),
            array('id' => 200, 'ar_name' => 'سيريلانكا', 'en_name' => 'Sri Lanka', 'code' => 'LKA'),
            array('id' => 201, 'ar_name' => 'السودان', 'en_name' => 'Sudan', 'code' => 'SDN'),
            array('id' => 202, 'ar_name' => 'سورينام', 'en_name' => 'Suriname', 'code' => 'SUR'),
            array('id' => 203, 'ar_name' => 'سفالبارد ويان ماين', 'en_name' => 'Svalbard and Jan Mayen', 'code' => 'SJM'),
            array('id' => 204, 'ar_name' => 'سوازيلاند', 'en_name' => 'Swaziland', 'code' => 'SWZ'),
            array('id' => 205, 'ar_name' => 'السويد', 'en_name' => 'Sweden', 'code' => 'SWE'),
            array('id' => 206, 'ar_name' => 'سويسرا', 'en_name' => 'Switzerland', 'code' => 'CHE'),
            array('id' => 207, 'ar_name' => 'سوريا', 'en_name' => 'Syrian Arab Republic', 'code' => 'SYR'),
            array('id' => 208, 'ar_name' => 'تايوان', 'en_name' => 'Taiwan, Province of China', 'code' => 'TWN'),
            array('id' => 209, 'ar_name' => 'طاجيكستان', 'en_name' => 'Tajikistan', 'code' => 'TJK'),
            array('id' => 210, 'ar_name' => 'جمهورية تنزانيا المتحدة', 'en_name' => 'Tanzania, United Republic of', 'code' => 'TZA'),
            array('id' => 211, 'ar_name' => 'تايلاند', 'en_name' => 'Thailand', 'code' => 'THA'),
            array('id' => 212, 'ar_name' => 'تيمور ليستي', 'en_name' => 'Timor-Leste', 'code' => '0'),
            array('id' => 213, 'ar_name' => 'توجو', 'en_name' => 'Togo', 'code' => 'TGO'),
            array('id' => 214, 'ar_name' => 'توكيلاو', 'en_name' => 'Tokelau', 'code' => 'TKL'),
            array('id' => 215, 'ar_name' => 'تونغا', 'en_name' => 'Tonga', 'code' => 'TON'),
            array('id' => 216, 'ar_name' => 'ترينيداد وتوباغو', 'en_name' => 'Trinidad and Tobago', 'code' => 'TTO'),
            array('id' => 217, 'ar_name' => 'تونس', 'en_name' => 'Tunisia', 'code' => 'TUN'),
            array('id' => 218, 'ar_name' => 'تركيا', 'en_name' => 'Turkey', 'code' => 'TUR'),
            array('id' => 219, 'ar_name' => 'تركمانستان', 'en_name' => 'Turkmenistan', 'code' => 'TKM'),
            array('id' => 220, 'ar_name' => 'جزر تركس وكايكوس', 'en_name' => 'Turks and Caicos Islands', 'code' => 'TCA'),
            array('id' => 221, 'ar_name' => 'توفالو', 'en_name' => 'Tuvalu', 'code' => 'TUV'),
            array('id' => 222, 'ar_name' => 'أوغندا', 'en_name' => 'Uganda', 'code' => 'UGA'),
            array('id' => 223, 'ar_name' => 'أوكرانيا', 'en_name' => 'Ukraine', 'code' => 'UKR'),
            array('id' => 224, 'ar_name' => 'الإمارات العربية المتحدة', 'en_name' => 'United Arab Emirates', 'code' => 'ARE'),
            array('id' => 225, 'ar_name' => 'المملكة المتحدة', 'en_name' => 'United Kingdom', 'code' => 'GBR'),
            array('id' => 226, 'ar_name' => 'الولايات المتحدة الأمريكية', 'en_name' => 'United States', 'code' => 'USA'),
            array('id' => 227, 'ar_name' => 'جزر الولايات المتحدة البعيدة الصغرى', 'en_name' => 'United States Minor Outlying Islands', 'code' => '0'),
            array('id' => 228, 'ar_name' => 'أوروغواي', 'en_name' => 'Uruguay', 'code' => 'URY'),
            array('id' => 229, 'ar_name' => 'أوزبيكستان', 'en_name' => 'Uzbekistan', 'code' => 'UZB'),
            array('id' => 230, 'ar_name' => 'فانواتو', 'en_name' => 'Vanuatu', 'code' => 'VUT'),
            array('id' => 231, 'ar_name' => 'فنزويلا', 'en_name' => 'Venezuela', 'code' => 'VEN'),
            array('id' => 232, 'ar_name' => 'فيتنام', 'en_name' => 'Viet Nam', 'code' => 'VNM'),
            array('id' => 233, 'ar_name' => 'جزر فيرجن البريطانية', 'en_name' => 'Virgin Islands, British', 'code' => 'VGB'),
            array('id' => 234, 'ar_name' => 'جزر فيرجن ، الولايات المتحدة', 'en_name' => 'Virgin Islands, U.s.', 'code' => 'VIR'),
            array('id' => 235, 'ar_name' => 'واليس وفوتونا', 'en_name' => 'Wallis and Futuna', 'code' => 'WLF'),
            array('id' => 236, 'ar_name' => 'الصحراء الغربية', 'en_name' => 'Western Sahara', 'code' => 'ESH'),
            array('id' => 237, 'ar_name' => 'اليمن', 'en_name' => 'Yemen', 'code' => 'YEM'),
            array('id' => 238, 'ar_name' => 'زامبيا', 'en_name' => 'Zambia', 'code' => 'ZMB'),
            array('id' => 239, 'ar_name' => 'زمب ـ ابوي', 'en_name' => 'Zimbabwe', 'code' => 'ZWE'),
            array('id' => 240, 'ar_name' => 'صربيا', 'en_name' => 'Serbia', 'code' => 'SRB'),
            array('id' => 241, 'ar_name' => 'منطقة آسيا والمحيط الهادئ', 'en_name' => 'Asia Pacific Region', 'code' => '0'),
            array('id' => 242, 'ar_name' => 'مونتينيغرو', 'en_name' => 'Montenegro', 'code' => 'MNE'),
            array('id' => 243, 'ar_name' => 'جزر آلاند', 'en_name' => 'Aland Islands', 'code' => 'ALA'),
            array('id' => 245, 'ar_name' => 'كوراساو', 'en_name' => 'Curacao', 'code' => 'CUW'),
            array('id' => 246, 'ar_name' => 'جيرنسي', 'en_name' => 'Guernsey', 'code' => 'GGY'),
            array('id' => 247, 'ar_name' => 'جزيرة آيل أوف مان', 'en_name' => 'Isle of Man', 'code' => 'IMN'),
            array('id' => 248, 'ar_name' => 'جيرسي', 'en_name' => 'Jersey', 'code' => 'JEY'),
            array('id' => 249, 'ar_name' => 'كوسوفو', 'en_name' => 'Kosovo', 'code' => '---'),
            array('id' => 250, 'ar_name' => 'سانت بارتيليمي', 'en_name' => 'Saint Barthelemy', 'code' => 'BLM'),
            array('id' => 252, 'ar_name' => 'سينت مارتن', 'en_name' => 'Sint Maarten', 'code' => 'SXM'),
            array('id' => 253, 'ar_name' => 'جنوب السودان', 'en_name' => 'South Sudan', 'code' => 'SSD')
        );
        $countries =  DB::table('conutries')->insert($countries);
    }
}